# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: angrywildabeast0
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shorten-urls
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shorten-urls

provider:
  name: aws
  runtime: nodejs22.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  redirect:
    handler: src/redirect.handler
    events:
      - httpApi:
          path: /redirect
          method: get
  createUrl:
    handler: src/createUrl.handler
    events:
      - httpApi:
          path: /createUrl
          method: post

plugins:
  - serverless-offline
